spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/art_or_photo?autoReconnect=true&useSSL=false
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        show_sql: true


image:
  path: path
